spring:
  datasource:
    username: postgres
    password: saran3112
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aggregator_db

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

